### ISSUE TITLE
Unrecognized metadata after updating COFH

### ISSUE THREAD

**Issue by cauliflower69** [carrotengineer/EnderTech#40]
http://pastebin.com/FsPr7yfD

**Comment by Drayshak** [comment]
I'm almost certain this is an ID mismatch somehow.

I added the offending metadata to the log in this case, feel free to try again with http://hopper.bunnies.io/job/EnderTech/372/ - it will still crash if the IDs are wrong, but the metadata causing the crash will appear in the error.

**Comment by cauliflower69** [comment]
Thanks for the speedy reply 

This is the updated crash report

http://pastebin.com/A9Mq383s

**Comment by Drayshak** [comment]
Yeah this is almost certainly an ID mismatch, nothing in my mod goes to metadata value 13. I have no idea what the problem is but it's very unlikely to be anything of mine.

It would have to be related to a Thermal Dynamics duct sitting next to something from EnderTech. Do you have anything like this in your world?

**Comment by cauliflower69** [comment]
There are no Thermal Dynamics items being used at all as this just happened after that mod was added.

**Comment by BBoldt** [comment]
Someone playing my modpack got this when generating a new world.

http://pastebin.ca/3017506

Pretty strange.

EnderTech-1.7.10-0.3.2.388
CoFHCore-[1.7.10]3.0.2-262
ThermalDynamics-[1.7.10]1.0.0-122
ThermalExpansion-[1.7.10]4.0.1-182
ThermalFoundation-[1.7.10]1.0.0-81

**Comment by BBoldt** [comment]
Actually, mine seems to be a lot different than the one in the OP. Apologies.

They just started the same way so I thought it might be the same issue.

**Comment by voxelcarrot** [comment]
No, you're right, I think they're exactly the same issue. I've had other people investigate it too, and it almost certainly isn't anything EnderTech is doing wrong. Sometimes IDs get broken by misbehaving mods, or adding and removing mods a lot in the same world - then it's random which mod ends up with the error. Seems pretty hard to diagnose, too :(

**Comment by BBoldt** [comment]
What would cause it to happen on a fresh world though? That's the part of mine that seems the strangest if it's an issue of adding or removing mods in the same world.

**Comment by voxelcarrot** [comment]
Do you have a list of mods?

**Comment by BBoldt** [comment]
It's a long list >.>

https://www.atlauncher.com/pack/MinecraftUnabridged/

**Comment by BBoldt** [comment]
Also it should be noted that I couldn't reproduce the issue myself. I've made many new worlds and never gotten it.

**Comment by voxelcarrot** [comment]
So, having a quick skim through, the one thing I do know of that has corrupted ID/metadata in the past is MineTweaker. Specifically, if you start the game up, enter a world, then quit to the main menu and enter a world again (even the same one), it either crashed or loaded and corrupted. I've no idea if that's fixed or not though.

**Comment by BBoldt** [comment]
o.O
Never have run into that issue before. 
I'll get the person who initially sent me the issue to chime in on this issue. He may have more information about it.
