### ISSUE TITLE
blocktankcontroller error

### ISSUE THREAD

**Issue by Fayini** [carrotengineer/EnderTech#48]
Hi, My client crashed and when I logged back in it caused my entire server to crash. Now whenever anyone is anywhere near the area I had walked into the same issue occurs to them. The crash report is what follows. 

http://pastebin.com/SsY4LhhB

I am hopeful you will be able to assist us. 
Thank you Fay

**Comment by voxelcarrot** [comment]
That error report is really strange, and I'm almost certain it's nothing I'm doing wrong. Could you try disabling FastCraft and see if it works?

**Comment by Fayini** [comment]
the problem is now that others are crashing as well even when i am not in game. i got the server crash report: 
http://pastebin.com/mXjfpRbf

hopefully this helps

Fay

**Comment by voxelcarrot** [comment]
This definitely looks like some sort of world corruption. Hopefully you have a recent backup to roll back to?

**Comment by Fayini** [comment]
i will talk to all my server people. Thank you for all of your help. If we come up with anything else I will message you. If you think of anything please let me know. I appreciate all of the time you spent helping me. 
Fay
