### ISSUE TITLE
Remove config limits on size, cap at MAX_INT

### ISSUE THREAD

**Issue by RikuSS4** [carrotengineer/EnderTech#51]
I suggest you add Bedrockium Ender Tanks for those with extra utilities installed. Storage capacity nearing that of bedrockium drum, but in tank form. I suggest this because I just see people using bedrockium drums all over the place because of the massive amount you can store in one easy to carry block. I would like to use your tanks, but the drums just offer so much more storage.

 I changed the config to see the maximum ender tanks could hold, and it tops out at 1,024,000 mB in a the smallest tank size of 3x3x3. The bedrockium drum can hold 65,536,000 mB in 1 block space.

**Comment by voxelcarrot** [comment]
I'm not sure balancing against something ridiculously powerful is a good idea. I'm happy enough with the tanks and balance as it stands, but I might look at increasing the config option limits so you could just make them equivalent if you wanted. It might quickly run in to integer overflow problems, though, so there might have to be a cap (where a larger tank wouldn't have any benefit).

**Comment by RoloEdits** [comment]
man this would be awesome i love the tanks but i have a lot of fluid so i use ExtraCells to store most large volume liquids if you could increase the amount that high that would be awsome

**Comment by RoloEdits** [comment]
this would go perfect with my 200 trillion rf storage

**Comment by carrotengineer** [comment]
Could someone ( @RoloEdits or @RikuSS4 ?) please test build 396, and let me know if it works as expected?

https://hopper.bunnies.io/job/EnderTech/396/

**Comment by RoloEdits** [comment]
Yes, this is exactly what I was hoping for, thank you very much.A quick question, if I wanted the max storage to be achieved in a 3 meter cube than would I take the max value and divided by 27? would that work as expected or is the value not by available air blocks inside?

**Comment by carrotengineer** [comment]
It's calculated exactly as before, but the absolute maximum you can store in any size of tank is capped at MAX_INT. Just set the multiplier to 2147483647 and you'll get it from a 1x1 interior.

If you actually want it to scale between 1 interior and 27 interior, you'd need to divide 2147483647 by 27, yes.

**Comment by RoloEdits** [comment]
Thank You, I understand now. I have never tried to target a size before so i didn't know if it was interior size or the full size of the multiblock that was use for calculating.
