### ISSUE TITLE
Rendering Life Essence in GUI

### ISSUE THREAD

**Issue by RoloEdits** [carrotengineer/EnderTech#52]
The Life Essence From BM Does not render in The Gui Of Tank

It Renders Out Side Just Fine
![2015-06-30_00 19 11](https://cloud.githubusercontent.com/assets/12489689/8425739/d7ac1e54-1ebd-11e5-9e81-aba36b37c739.png)

But Not In The Gui
![2015-06-30_00 19 19](https://cloud.githubusercontent.com/assets/12489689/8425743/dd756e80-1ebd-11e5-9bc0-19b455e93e63.png)

**Comment by carrotengineer** [comment]
My gut feeling is that this is a problem with Life Essence, but I'll investigate it when I get some time.

**Comment by RoloEdits** [comment]
it also seems to be happening with water now too.

![2015-09-08_16 28 50](https://cloud.githubusercontent.com/assets/12489689/9749965/cf0a1150-5646-11e5-9b4d-17e821f04132.png)

**Comment by carrotengineer** [comment]
That might be a bug relating to ridiculous amounts of fluid in the tank - I'll investigate that too.

**Comment by RoloEdits** [comment]
Thanks, I was thinking it might have something to do with that.

**Comment by carrotengineer** [comment]
Could you please try build 398 - water renders correctly for me, but I'm not sure about life essence.

https://hopper.bunnies.io/job/EnderTech/398/

**Comment by RoloEdits** [comment]
Yes, both water and life essence are rendering correctly. Thank You very much for spending time to find a solution, it's very appreciated.

**Comment by carrotengineer** [comment]
Build 398 has been submitted to Curse with these changes, and will be available here when approved. http://minecraft.curseforge.com/mc-mods/223428-endertech/files/2256360 :)
