### ISSUE TITLE
Increase Amount Of Power the Energy Input Can Receive? 

### ISSUE THREAD

**Issue by RoloEdits** [carrotengineer/EnderTech#53]
When Wanting To Move large Amounts Of Liquids Its Fast At First The Slow Down Because What I'm Assuming Is The Amount  of Power The Energy Input Can Accept Is A Bottle Neck.

**Comment by carrotengineer** [comment]
@RoloEdits could you please try build 397 - a configuration item has been added to general.cfg, "I:Tank.MaxEnergyInputRate", where you can manually set the Ender Tank's input rate to whatever you want (capped at MAX_INT).

https://hopper.bunnies.io/job/EnderTech/397/

**Comment by RoloEdits** [comment]
Iv'e tried it and it works just fine, thanks for implementing it, it is greatly appreciated. something I might change though is if you make the number larger than the max it changed the values back to default, could you make it if you go to high to set it the the max and not the default.

**Comment by carrotengineer** [comment]
I think that's a Forge thing - if you give it something that isn't an integer it'll revert to the default.

**Comment by RoloEdits** [comment]
OK, its not to big of a deal, it takes 2 seconds to google it so I wouldn't worry about it to much.
