### ISSUE TITLE
Creative Exchanger causing out of bounds exception

### ISSUE THREAD

**Issue by CaptainHawaii** [carrotengineer/EnderTech#58]
[Pastebin](http://pastebin.com/W43LFL3Z)

Caused on right click, with any block selected.
Shift-right click can be done with no error.

**Comment by carrotengineer** [comment]
Yeah, I broke it in the last build by mistake. Thanks for the report!

It'll appear here when Curse Forge review the upload: http://minecraft.curseforge.com/mc-mods/223428-endertech/files/2256234 (build 395).
